// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nebqmtmzilybgfmbfajx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lYnFtdG16aWx5YmdmbWJmYWp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3OTk0NjIsImV4cCI6MjA1NTM3NTQ2Mn0.Tc4tTuBhvuHcjKDJ4E274ufPEbfjC99shWTTVyxzJbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);